[package]
name = "nu_plugin_todotxt"
version = "0.3.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
dirs = "6.0.0"
nu-plugin = "0.104.0"
nu-protocol = "0.104.0"
serde_json = "1.0.140"
thiserror = "2.0.12"
todo-txt = { version = "4.1.1", features = ["serde"] }
